import '../home.html'
import './scss/parent-style.css'
import './scss/home.scss'
import './scss/font-awesome.min.css'
import './scss/iconsmind.min.css'
import './js/jquery.numscroll.js'
import './js/ScrollMagic.min.js'
import './js/homeScript.js'
